steps:
  - task: AzureFunctionApp@1
    displayName: "Deploy Azure Function App to slot"
    inputs:
      azureSubscription: "$(azureSubscription)"
      appType: functionApp
      appName: "func-$(functionAppName)-$(environmentName)"
      package: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
      deployToSlotOrASE: true
      resourceGroupName: "$(rgName)"
      slotName: "Staging"

  - task: AzureAppServiceManage@0
    displayName: 'Start Staging Slot'
    inputs:
      azureSubscription: '$(azureSubscription)'    
      Action: 'Start Azure App Service'
      WebAppName: 'func-$(functionAppName)-$(environmentName)'
      SpecifySlotOrASE: true
      ResourceGroupName: "$(rgName)"
      Slot: Staging  