steps:
  - task: AzureResourceManagerTemplateDeployment@3    
    displayName: 'Create app service plan'
    inputs:
      deploymentScope: 'Resource Group' 
      azureResourceManagerConnection: '$(azureSubscription)' 
      location: 'Australia Southeast' 
      action: 'Create Or Update Resource Group' 
      resourceGroupName: '$(rgName)'
      deploymentMode: 'Incremental' 
      csmFile: '$(Pipeline.Workspace)/deploy/AppServicePlan/template.json' 
      csmParametersFile: '$(Pipeline.Workspace)/deploy/AppServicePlan/template.parameters.json' 
      overrideParameters: |
        -planName "plan-$(functionAppName)-$(environmentName)" 
      