steps:
  - task: AzureResourceManagerTemplateDeployment@3    
    displayName: 'Create storage account'
    inputs:
      deploymentScope: 'Resource Group' 
      azureResourceManagerConnection: '$(azureSubscription)' 
      location: 'Australia Southeast' 
      action: 'Create Or Update Resource Group' 
      resourceGroupName: '$(rgName)'
      deploymentMode: 'Incremental' 
      csmFile: '$(Pipeline.Workspace)/deploy/StorageAccount/template.json' 
      csmParametersFile: '$(Pipeline.Workspace)/deploy/StorageAccount/template.parameters.json' 
      overrideParameters: |
        -sgName "st$(functionAppName)$(environmentName)" 
        -sgType "Standard_GRS" 
      